<Workspace Version="1.3.3.4111" X="-43.5709543062559" Y="4.4836313578669" zoom="0.717322426435809" ScaleFactor="1" Name="Curve.DivideSegments" Description="Divides curve into equal segments using hmin and returns points and station values." ID="af04c844-0b4d-4a21-b489-76a41fee4903" Category="SofiLink.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="52f1dada-c307-4e23-bc5c-f6129b89d70b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="203.2" y="214.833568566627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="curves:Curve[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3a199bf2-fd6c-49cf-95fd-bda9327b8915" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="205.213763691008" y="278.50503363663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="hmin:double = 1.0" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="df2ef099-56b8-4f1b-8078-53e20937bd74" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1907.28544898769" y="240.816529806281" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="points" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e7d9f0c2-5a88-4966-85eb-d93976667d16" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1912.98175959682" y="455.392962533806" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="stations" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="843153bc-a5a0-49da-8ae5-b9df533b877e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1126.68898948682" y="13.0491214078954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="placements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="6684ecd2-4db8-43d6-844a-3046a8976b67" type="PythonNodeModels.PythonNode" nickname="Curve.ToPlacements" x="945.014872473396" y="11.8919614269181" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
if isinstance(IN[0], list):
	OUT = [IN[0][0].StartPoint]
	for curve in IN[0]:
		OUT.append(curve.EndPoint)
else:
	OUT = [IN[0].StartPoint, IN[0].EndPoint]
	

OUT</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b256befd-6377-4891-915c-729dc139e72d" type="PythonNodeModels.PythonNode" nickname="Point.DivideSegments" x="559.116663669676" y="330.036434631011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
if isinstance(IN[0], list):
	lengths = [curve.Length for curve in IN[0]]
	hmin = IN[1]
	divisions = [round(length/hmin) for length in lengths]
	for i, division in enumerate(divisions):
		if division == 0:
			divisions[i] = 1
else:
	hmin = IN[1]
	divisions = round(IN[0].Length/hmin)
	if divisions == 0:
		divisions[i] = 1

OUT = divisions</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2a547f01-dc6e-406b-b17f-e1d5f0a3a211" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.PointsAtEqualSegmentLength" x="837.564159398431" y="186.004488662891" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength@int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a265ba46-56a8-4ba1-8da7-8c0ed598c0d6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.SegmentLengthAtParameter" x="950.832197338382" y="452.283791124901" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.SegmentLengthAtParameter@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="c8f8ab47-1759-4378-8b39-a89cd1d84013" type="PythonNodeModels.PythonNode" nickname="Segments.AddStartAndEndPoint" x="1166.87378491163" y="281.109222038841" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
divisions = []
if isinstance(IN[1],list):
	curvepoints = [[curve.StartPoint, curve.EndPoint] for curve in IN[1]]
	
	for segment, ends in zip(IN[0],curvepoints):
		divisions.append([ends[0]] + segment + [ends[-1]])
		
	OUT = divisions
else:
	OUT = [IN[1].StartPoint, IN[0], IN[1].EndPoint]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="162c94b6-ae4e-4748-ba8a-ef3fe3ab7664" type="PythonNodeModels.PythonNode" nickname="Parameters" x="779.960145240786" y="491.560066794796" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = []
if isinstance(IN[0],list):
	for length in IN[0]:
		parameters = []
		if length &gt; 1:
			for parameter in range(int(length)+1):
				parameters.append(parameter/(length))
		else:
			parameters = [0, 1]
		OUT.append(parameters)
else:
	length = IN[0]
	parameters = []
	if length &gt; 1:
		for parameter in range(int(length)+1):
			parameters.append(parameter/(length))
	else:
		parameters = [0, 1]
	OUT= parameters


OUT</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="9fde397a-26fa-4920-ba34-3253cf15ee09" type="PythonNodeModels.PythonNode" nickname="Stations" x="1261.21600702236" y="522.68973398043" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
val = 0
OUT = []
if isinstance(IN[0][0],list):

	for segment in IN[0]:
		stations = [round(val + station, 3) for station in segment]
		val += segment[-1]
		OUT.append(stations)
else:
	OUT = [round(station, 3) for station in IN[0]]
OUT</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="67be722a-2ebb-40f7-9a05-e7f146e171a8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1481.36060475526" y="247.704813103431" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0d0d0619-428c-4f42-8588-a5877ef5a825" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1484.45786722161" y="469.476632866975" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="08a96409-3553-4db4-9727-2fb65b1c2add" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.UniqueItems" x="1714.64974485693" y="238.54057738584" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.UniqueItems@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7c78829f-6954-4a75-a79c-d022bcd535e3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.UniqueItems" x="1717.74700732329" y="460.312397149379" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.UniqueItems@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="52f1dada-c307-4e23-bc5c-f6129b89d70b" start_index="0" end="6684ecd2-4db8-43d6-844a-3046a8976b67" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52f1dada-c307-4e23-bc5c-f6129b89d70b" start_index="0" end="b256befd-6377-4891-915c-729dc139e72d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52f1dada-c307-4e23-bc5c-f6129b89d70b" start_index="0" end="2a547f01-dc6e-406b-b17f-e1d5f0a3a211" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52f1dada-c307-4e23-bc5c-f6129b89d70b" start_index="0" end="c8f8ab47-1759-4378-8b39-a89cd1d84013" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52f1dada-c307-4e23-bc5c-f6129b89d70b" start_index="0" end="a265ba46-56a8-4ba1-8da7-8c0ed598c0d6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3a199bf2-fd6c-49cf-95fd-bda9327b8915" start_index="0" end="b256befd-6377-4891-915c-729dc139e72d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6684ecd2-4db8-43d6-844a-3046a8976b67" start_index="0" end="843153bc-a5a0-49da-8ae5-b9df533b877e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b256befd-6377-4891-915c-729dc139e72d" start_index="0" end="162c94b6-ae4e-4748-ba8a-ef3fe3ab7664" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b256befd-6377-4891-915c-729dc139e72d" start_index="0" end="2a547f01-dc6e-406b-b17f-e1d5f0a3a211" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a547f01-dc6e-406b-b17f-e1d5f0a3a211" start_index="0" end="c8f8ab47-1759-4378-8b39-a89cd1d84013" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a265ba46-56a8-4ba1-8da7-8c0ed598c0d6" start_index="0" end="9fde397a-26fa-4920-ba34-3253cf15ee09" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8f8ab47-1759-4378-8b39-a89cd1d84013" start_index="0" end="67be722a-2ebb-40f7-9a05-e7f146e171a8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="162c94b6-ae4e-4748-ba8a-ef3fe3ab7664" start_index="0" end="a265ba46-56a8-4ba1-8da7-8c0ed598c0d6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9fde397a-26fa-4920-ba34-3253cf15ee09" start_index="0" end="0d0d0619-428c-4f42-8588-a5877ef5a825" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="67be722a-2ebb-40f7-9a05-e7f146e171a8" start_index="0" end="08a96409-3553-4db4-9727-2fb65b1c2add" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d0d0619-428c-4f42-8588-a5877ef5a825" start_index="0" end="7c78829f-6954-4a75-a79c-d022bcd535e3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="08a96409-3553-4db4-9727-2fb65b1c2add" start_index="0" end="df2ef099-56b8-4f1b-8078-53e20937bd74" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7c78829f-6954-4a75-a79c-d022bcd535e3" start_index="0" end="e7d9f0c2-5a88-4966-85eb-d93976667d16" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="7baaac82-bc34-4c41-9042-e32e3b53c4c8" text="returns an array of procentual values based on the provided hmin value" x="501.33363662021" y="422.571266322703" />
    <Dynamo.Graph.Notes.NoteModel guid="8b81abce-4422-4d55-b473-79d72eeb1bf0" text="similar to the succeeding node it returns the parameters of the curve" x="718.330952998634" y="562.431727040617" />
    <Dynamo.Graph.Notes.NoteModel guid="4fd4ff76-940e-4ca0-86b3-7c9c252e0ca8" text="converts the segment length array to station values" x="1185.8754818844" y="583.65001186351" />
    <Dynamo.Graph.Notes.NoteModel guid="3012c245-8744-430e-b973-5c2cad188e5a" text="adds the start and end point to the array of points" x="1137.33907384395" y="371.837489232374" />
    <Dynamo.Graph.Notes.NoteModel guid="f560cae9-468c-4c55-8f80-33a42b6b902c" text="selects the placement points from the supplied array" x="866.075694665869" y="79.2582253861531" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="17.034891221023" eyeY="72.4416454683278" eyeZ="22.1939415043898" lookX="33.236946105957" lookY="-33.6270217895508" lookZ="-8.72614097595215" upX="0.512548863887787" upY="0.848048090934753" upZ="-0.134566321969032" />
  </Cameras>
</Workspace>