<Workspace Version="1.3.3.4111" X="83.79" Y="42.336" zoom="0.8425" ScaleFactor="1" Name="DAT.ReadParameterValuesFromFile" Description="Reads from the 'parameter file' the parameter values at each station along the bridge axis 'A1'." ID="b9d3e434-af8a-477a-a2c4-db1a69f4de92" Category="SofiLink.Core.File">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="851f3333-ced9-447a-9c4c-f5cf7ba2d67e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="File.ReadText" x="467.087830109326" y="312" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.IO.File.ReadText@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="6201c4b6-d292-441e-90ec-23a3de7cf9fd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="249.6" y="314.234902101772" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = '.\\' + str(IN[0]) + '.dat'</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2455f44c-2415-4c2d-801f-82696cb21704" type="PythonNodeModels.PythonNode" nickname="Python Script" x="707.714844827236" y="153.43475766346" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

varvals = []

for line in IN[1].split('\n'):
	if line.startswith("\tA1"):
		var = line.split('\t')
		if var[2] == str(IN[0]):
			varvals.append(float(var[-2]))

#Assign your output to the OUT variable.

OUT = varvals</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6c0a631d-072a-4f36-a06a-2139ffba8c8f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="33.6" y="224.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="name: var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="57198e51-9d0d-49ad-9064-b21fe5fb4c33" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="939.2" y="154.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="values" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="851f3333-ced9-447a-9c4c-f5cf7ba2d67e" start_index="0" end="2455f44c-2415-4c2d-801f-82696cb21704" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6201c4b6-d292-441e-90ec-23a3de7cf9fd" start_index="0" end="851f3333-ced9-447a-9c4c-f5cf7ba2d67e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2455f44c-2415-4c2d-801f-82696cb21704" start_index="0" end="57198e51-9d0d-49ad-9064-b21fe5fb4c33" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c0a631d-072a-4f36-a06a-2139ffba8c8f" start_index="0" end="6201c4b6-d292-441e-90ec-23a3de7cf9fd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c0a631d-072a-4f36-a06a-2139ffba8c8f" start_index="0" end="2455f44c-2415-4c2d-801f-82696cb21704" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>