<Workspace Version="1.3.3.4111" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Point.ToSegments" Description="Seperates list of section positions into segement lists" ID="ff481381-0dab-4b37-87d4-307e26b5433c" Category="SofiLink.Geometry.Point">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="40aa6c1f-7969-45ef-a7b7-7bf9b0cb9c84" type="PythonNodeModels.PythonNode" nickname="Point.ToSegments" x="401.6" y="325.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
segments = []
sub = []

for i in range(len(IN[0])-1):
	if (abs(IN[0][i].X - IN[0][i+1].X) &lt; 1e-2 and
		abs(IN[0][i].Y - IN[0][i+1].Y) &lt; 1e-2 and
		abs(IN[0][i].Z - IN[0][i+1].Z) &lt; 1e-2):
		
		sub.append(IN[0][i])
		segments.append(sub)
		sub = []
		
	else:
		sub.append(IN[0][i])
		
sub.append(IN[0][-1])
segments.append(sub)

OUT = segments</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="316c48dd-0d38-4224-a52d-7fc8cfc81abf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="138.4" y="322.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="points:Point[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4b42b7f9-2169-461b-a5e9-77607b303dd5" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="642.4" y="325.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="segments" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="40aa6c1f-7969-45ef-a7b7-7bf9b0cb9c84" start_index="0" end="4b42b7f9-2169-461b-a5e9-77607b303dd5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="316c48dd-0d38-4224-a52d-7fc8cfc81abf" start_index="0" end="40aa6c1f-7969-45ef-a7b7-7bf9b0cb9c84" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="36.0882759094238" eyeY="15.4076404571533" eyeZ="10.7589015960693" lookX="-2.3368034362793" lookY="-17.592643737793" lookZ="-9.72553634643555" upX="-0.173617780208588" upY="0.669130623340607" upZ="-0.722579479217529" />
  </Cameras>
</Workspace>