<Workspace Version="1.3.3.4111" X="189.324928173914" Y="-15.4902278015288" zoom="1.16438980805626" ScaleFactor="1" Name="List.IndicesOfItems" Description="returns indices of items' occurence in list " ID="c8797c08-c3c0-4f42-96e6-70729a3cf4b6" Category="SofiLink.Core">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8a88cd39-660f-4489-91fa-76e6c2b1094c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="68.7131057380727" y="153.866738761617" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="items:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="35b66b90-c6eb-48a7-8980-da3e78baad4a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="70.7268694290806" y="217.53820383162" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="list:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9c68dd78-d1ca-46ce-bd5e-c6297420e770" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="488.459466213014" y="167.430327704894" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="indices" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="39e73a0e-484c-480d-b9ae-c4e1c06ec15a" type="PythonNodeModels.PythonNode" nickname="List.Indices" x="281.597090349616" y="161.398363913413" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
indices = []
for item in IN[0]:
	for i, litem in enumerate(IN[1]):
		if item == litem: #(placement.X == point.X and placement.Y == point.Y and placement.Z == point.Z):
			indices.append(i)
			
OUT = indices</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8a88cd39-660f-4489-91fa-76e6c2b1094c" start_index="0" end="39e73a0e-484c-480d-b9ae-c4e1c06ec15a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="35b66b90-c6eb-48a7-8980-da3e78baad4a" start_index="0" end="39e73a0e-484c-480d-b9ae-c4e1c06ec15a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="39e73a0e-484c-480d-b9ae-c4e1c06ec15a" start_index="0" end="9c68dd78-d1ca-46ce-bd5e-c6297420e770" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="36.0882759094238" eyeY="15.4076404571533" eyeZ="10.7589015960693" lookX="-2.3368034362793" lookY="-17.592643737793" lookZ="-9.72553634643555" upX="-0.173617780208588" upY="0.669130623340607" upZ="-0.722579479217529" />
  </Cameras>
</Workspace>