<Workspace Version="1.3.3.4111" X="0" Y="0" zoom="1" ScaleFactor="1" Name="List.RemoveItems" Description="removes given items from list" ID="66753114-2624-4680-a2e7-f0076a9b6264" Category="SofiLink.Core.List">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ec49a42a-ea1d-4583-b4f4-a783ff00cf7e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1053.80582668795" y="204.193916648171" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="list" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="d375b378-8f21-4d44-8804-83a03d4dad64" type="PythonNodeModels.PythonNode" nickname="List.RemoveItems" x="806.4" y="194.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.

OUT = [index for index in IN[1] if not index in IN[0]]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f8a5bf36-b3ee-4c54-85e2-4f190f51a891" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="545.6" y="200.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="items: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="959be92f-235f-4a16-bcfd-b5c5b88b5ad0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="544.8" y="280.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="list: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d375b378-8f21-4d44-8804-83a03d4dad64" start_index="0" end="ec49a42a-ea1d-4583-b4f4-a783ff00cf7e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f8a5bf36-b3ee-4c54-85e2-4f190f51a891" start_index="0" end="d375b378-8f21-4d44-8804-83a03d4dad64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="959be92f-235f-4a16-bcfd-b5c5b88b5ad0" start_index="0" end="d375b378-8f21-4d44-8804-83a03d4dad64" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="36.0882759094238" eyeY="15.4076404571533" eyeZ="10.7589015960693" lookX="-2.3368034362793" lookY="-17.592643737793" lookZ="-9.72553634643555" upX="-0.173617780208588" upY="0.669130623340607" upZ="-0.722579479217529" />
  </Cameras>
</Workspace>